### ISSUE TITLE
关于项目的运行

### ISSUE THREAD

**Issue by Dyer233** [zysszy/TreeGen#27]
你好，TreeGen对应的TensorFlow版本为1.12.0，其对应的cuda版本为9.0,我在使用RTX3090运行项目的时候会出现cuda版本不兼容的报错,查詢過一些帖子有說到30系显卡无法兼容TensorFlow1.版本，請問有什麽辦法能夠解決這個問題嗎？

**Comment by zysszy** [comment]
您好，非常抱歉回复晚了，最近没有看GitHub。

确实会存在这种问题，项目确实过于老化了。

为了解决这个问题，我刚刚提供了一个 pytorch 版本的 TreeGen 模型 （https://github.com/zysszy/TreeGen-Pytorch/tree/main），希望能帮助到你。

Zeyu
