### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by iamxpy** [zysszy/TreeGen#6]
After we got the model checkpoint after training for enough epochs, I tried to run `predict.py` for inference, but got the following error.

```
Traceback (most recent call last):
  File "predict.py", line 615, in <module>
    main()
  File "predict.py", line 613, in main
    predict()
  File "predict.py", line 600, in predict
    BeamSearch(sess, Code_gen_model, Nl, int(sys.argv[2]), i)
  File "predict.py", line 488, in BeamSearch
    list_res = sorted(list_res, reverse=True)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Is this a bug?

**Comment by zysszy** [comment]
I am sorry for this bug. 
This can be fixed by 
```
try:
    list_res = sorted(list_res, reverse=True)
except:
    JavaOut.is_end = True
    Set_.put(JavaOut)
    continue
```

Zeyu

**Comment by iamxpy** [comment]
> I am sorry for this bug.
> This can be fixed by
> 
> ```
> try:
>     list_res = sorted(list_res, reverse=True)
> except:
>     JavaOut.is_end = True
>     Set_.put(JavaOut)
>     continue
> ```
> 
> Zeyu

Thanks for the quick reply!
